#descbrindo os metodos de manipulaçao de string(superficial)

info = (input('digite algo:'))
print(type(info))
print(info.isalpha())
print(info.isnumeric())
print(info.isdecimal())
print(info.isalnum())
print(info.isascii())
print(info.isdigit())
print(info.isidentifier())
print(info.isupper())
print(info.islower())
print(info.isprintable())
print(info.isspace())
print(info.istitle())
